haskell-servant/servant-auth

- servant-auth-server/src/Servant/Auth/Server/Internal/ConfigTypes.hs
- servant-auth-server/src/Servant/Auth/Server/Internal/Cookie.hs
Hi Julian,
Here's a change to make the session cookie name configurable, if you're interested in supporting that. The cookie name still defaults to `JWT-Cookie`.
Thanks,
Brian
> Make session cookie name configurable

- README.md
- servant-auth-server/executables/README.lhs
The unprotected route in the example matches first on the `Raw` route and then on the `"login"` route. A query to the login route gives the following result:
$ curl localhost:7249/login -v
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 7500 (#0)
> GET /login HTTP/1.1
> Host: localhost:7500
> User-Agent: curl/7.47.1
> Accept: */*
> 
< HTTP/1.1 404 Not Found
< Transfer-Encoding: chunked
< Date: Sun, 05 Feb 2017 12:12:54 GMT
< Server: Warp/3.2.9
< Content-Type: text/plain
< 
* Connection #0 to host localhost left intact
File not found%    
If there is a file called `login` in the static folder the content of this file is served. 
$ curl localhost:7249/login -v 
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 7500 (#0)
> GET /login HTTP/1.1
> Host: …
> Change routing order for unprotected route

- servant-auth-swagger/.ghci
- servant-auth-swagger/LICENSE
- servant-auth-swagger/Setup.hs
- servant-auth-swagger/package.yaml
- servant-auth-swagger/servant-auth-swagger.cabal
- servant-auth-swagger/src/Servant/Auth/Swagger.hs
- servant-auth-swagger/test/Doctest.hs
- servant-auth-swagger/test/Servant/Auth/SwaggerSpec.hs
- servant-auth-swagger/test/Spec.hs
- stack.yaml
This PR adds a new package, which supports `servant-swagger`.
> servant-auth-swagger

- .travis.yml
- servant-auth-client/package.yaml
- servant-auth-client/servant-auth-client.cabal
- servant-auth-docs/package.yaml
- servant-auth-docs/servant-auth-docs.cabal
- servant-auth-server/package.yaml
- servant-auth-server/servant-auth-server.cabal
- servant-auth-swagger/package.yaml
- servant-auth-swagger/servant-auth-swagger.cabal
- servant-auth/package.yaml
- servant-auth/servant-auth.cabal
- stack-ghc-8.2.1.yaml
Created `stack-ghc-8.2.1.yaml` which contains resolver `nightly-2017-09-07`.
Updated `travis.yaml` and increased upper bounds of some dependencies. Could not update `jose` to latest version (0.6.0.3) because it contains large changes and also not the purpose of this PR.
> Support for GHC 8.2.1

- servant-auth-server/src/Servant/Auth/Server.hs
- servant-auth-server/src/Servant/Auth/Server/Internal.hs
- servant-auth-server/src/Servant/Auth/Server/Internal/ConfigTypes.hs
- servant-auth-server/src/Servant/Auth/Server/Internal/Cookie.hs
Fixes #53 
This got me thinking: the CSRF protection could probably be entirely "pluggable". When it comes to security, you don't necessarily want that much flexibility though.
This doesn't pass tests yet but I wanted to see what you thought of the approach. I don't like how it sets an empty cookie just to get two set-cookie headers to make the types happy.
> RFC: Add check-origin method for CSRF

- servant-auth-server/servant-auth-server.cabal
It has trouble dealing with the .lhs file.
> Disable the readme executable for ghcjs builds

- servant-auth-server/src/Servant/Auth/Server/Internal/AddSetCookie.hs
Make AddSetCookieApi open, so it's possible to implement that
type family for endpoint that are defined by the user.
Additional closed type family is used to resolve overlap in
instance declarations for Verb.
Resolves #84.
> Make AddSetCookieApi type family open.

- servant-auth-server/src/Servant/Auth/Server/Internal/ConfigTypes.hs
- servant-auth-server/src/Servant/Auth/Server/Internal/Cookie.hs
- servant-auth-server/test/Servant/Auth/ServerSpec.hs
The default is the same as before i.e. to perform CSRF checks for all methods
by setting {xsrfExcludeGet = True} the check can be disabled for GET
fixes #77
> Make CSRF checks optional for GET requests (see #77)

- servant-auth-swagger/src/Servant/Auth/Swagger.hs
Hi Servant-Authors,
I've been writing a [little servant webapp](https://github.com/sordina/freewill.it#freewillai)
and have encountered two issues with the cookie auth behaviour in servant-auth.
The second is simple: There isn't a swagger AllHasSecurity instance for Cookie. After reading through the swagger docs and Haskell swagger issues, it looks like there's no good instance for this currently, but in order for our apps to use both swagger and cookies, we need something, so I've added an instance that simply ignores cookies for now. Another option would be to make the private module a public (Internal) module so that developers could add their own workaround instance.
The first is more interesting: The cookie settings from servant-auth-server/src/Servant/Auth/Server/Internal/Cookie.hs …
> Global Cookie Path and Swagger Cookie Instances

- servant-auth-swagger/test/Servant/Auth/SwaggerSpec.hs
- stack.yaml
Since the Cookie instance doesn't add any docs, I didn't think of what else could we check.
PS: without the stack.yaml the project wouldn't compile.
> servant-auth-swagger: add Cookie to the test

- servant-auth-server/src/Servant/Auth/Server/Internal/ConfigTypes.hs
- servant-auth-server/src/Servant/Auth/Server/Internal/JWT.hs
Default algorithm generates pretty long tokens, I'd prefer using HS256 and this PR allows to do that.
> makeJWT: allow setting Alg via defaultJWTSettings

- servant-auth-server/src/Servant/Auth/Server/Internal/ConfigTypes.hs
- servant-auth-server/src/Servant/Auth/Server/Internal/Cookie.hs
- servant-auth-server/src/Servant/Auth/Server/Internal/JWT.hs
This is useful if you rotate keys with short expiration time.
> Validate JWT against a JWKSet instead of JWK

- servant-auth-server/src/Servant/Auth/Server/Internal/Cookie.hs
Currently the JWT session cookie does not expire, it should be set to expire to enforce serverside cookie expiration.
If an attacker were to get there hands on a JWT cookie, they could use it to stay authenticated until the server's JWT key is changed.
This PR allows you to make the cookie expire by setting the cookieExpires field of cookieSettings, but this is an absolute time argument, and would need to be different for each issued cookie.
A better solution might be to use the cookieMaxAge field (which is DiffTime) to generate the expiration time for the JWT. Its probably also a good idea to set the default cookieMaxAge to something like 30 days. If you think this is a good idea I can modify the PR as necessary.
> Make cookies expire serverside

- servant-auth-server/src/Servant/Auth/Server.hs
Added example for using `hoistServerWithContext` (#108)
Would have liked to use doctest, but seems it doesn't work with documentation inside module clauses.
> Add documentation for using custom handler

- servant-auth-server/src/Servant/Auth/Server/Internal/Cookie.hs
This means previously, protection of the cookie wasn't applied. 
cc @3noch
> Session cookie didn't apply SameSite attribute

- servant-auth-swagger/src/Servant/Auth/Swagger.hs
Closes #114.
From what I can understand, in order to define a [`HasSwagger` instance for an API that has an authentication method](https://github.com/haskell-servant/servant-auth/blob/master/servant-auth-swagger/src/Servant/Auth/Swagger.hs#L28), an `AllHasSecurity` instance is required for the authentication method, which can be built incrementally for the intended service from [these](https://github.com/haskell-servant/servant-auth/blob/master/servant-auth-swagger/src/Servant/Auth/Swagger.hs#L59) [two](https://github.com/haskell-servant/servant-auth/blob/master/servant-auth-swagger/src/Servant/Auth/Swagger.hs#L73) instances.
For this method to work, `HasSecurity` has to be exported (the previous two instances are exported automatically), which is what this PR does.
> [#114] Export `HasSecurity` typeclass

- servant-auth-server/src/Servant/Auth/Server/Internal/Types.hs
Checks made after first not Indefinite result are ignored in Semigroup instance.
With this change change we avoid running checks whose results will be thrown out later.
Another advantage of this change is ability to specifying more expensive checks after cheaper checks, and avoiding running more expensive ones if cheaper succeeds.
For example you may have "access token"-like cookie which times out with session and does not require DB access, and optional "remember-me" cookie which does requires DB access. With this change you can avoid accessing DB while session cookie is still alive.
This is a breaking change for users who have side-effecting auth checks that rely on the fact that all checks are run on each request.
> Avoid running auth checks unnecessarily

- .travis.yml
- servant-auth-client/servant-auth-client.cabal
- servant-auth-client/test/Servant/Auth/ClientSpec.hs
- servant-auth-docs/servant-auth-docs.cabal
- servant-auth-server/servant-auth-server.cabal
- servant-auth-swagger/servant-auth-swagger.cabal
- servant-auth/servant-auth.cabal
Fix #144 
@phadej should we mention in changelog that `GenResponse` is now `ResponseF`? This was public api in  `servant-client`
> Fix #144: servant-0.16 support in tests

- servant-auth-server/src/Servant/Auth/Server/Internal.hs
There is an unused constraint in the `HasServer` instance for `Auth`, so this PR removes it.
I also took the liberty to further simplify the type signature.
> remove unused constraint in HasServer instance for Auth

- servant-auth-server/src/Servant/Auth/Server/Internal/Types.hs
Small fix to get this working with 8.8.1.
> Extract fail method from Monad AuthCheck

- servant-auth-server/src/Servant/Auth/Server/Internal/BasicAuth.hs
This PR just adds documentation to `BasicAuthCfg`, the type used for configuring Basic Authentication.
The definition of `BasicAuthCfg` as a type family without arguments may surprise new users, so I added a short explanation. I also added a couple of simple usage examples.
> Document BasicAuthCfg

- servant-auth-server/src/Servant/Auth/Server.hs
- servant-auth-server/src/Servant/Auth/Server/Internal.hs
- servant-auth-server/src/Servant/Auth/Server/Internal/Class.hs
- servant-auth-server/src/Servant/Auth/Server/Internal/Cookie.hs
- servant-auth-server/src/Servant/Auth/Server/Internal/JWT.hs
- servant-auth/servant-auth.cabal
- servant-auth/src/Servant/Auth/JWT.hs
I was experimenting with various things in this library this morning, and I saw issue #135 and thought to try to put together a solution.
I reexported `ToJWT` and `FromJWT` from `servant-auth-server` to keep things consistent for users. 
Fixes #135
> First pass: move ToJWT/FromJWT to servant-auth

- servant-auth-server/src/Servant/Auth/Server/Internal/Cookie.hs
`AnySite` in `CookieSettings` doesn't work. It was consequence from lack of such setting in the `cookie` package in the past.
But now there is `sameSiteNone` option for Cookies (`cookie >= 0.4.5`) which is corresponding to `AnySite`. So this patch fix it.
> Fix: AnySite

- .github/workflows/ci.yml
- servant-auth-client/servant-auth-client.cabal
- servant-auth-docs/servant-auth-docs.cabal
- servant-auth-server/README.lhs
- servant-auth-server/servant-auth-server.cabal
- servant-auth-swagger/servant-auth-swagger.cabal
- servant-auth/servant-auth.cabal
- stack-lts16.yaml
I've made some updates to the `servant-auth` CI setup to try and bring them up to speed with the official [haskell/actions](github.com/haskell/actions) GitHub Actions (since neither [bubba/setup-haskell](github.com/bubba/setup-haskell) or [actions/haskell](github.com/actions/setup-haskell) are actively maintained).
Aside from just doing a little cleaning, I've also made the following opinionated changes:
- dropped the macOS runners
- since this is a library (and not an application) without any dynamic library or C deps, having the extra runners just seemed like more noise in the matrix
- dropped GHC 8.2 and 8.4
- I don't typically see much point in actively supporting GHC versions older than the last 3 major releases
- that being said, I guess compute is pretty cheap; if y'all would …
> Updates CI and README badges

- .github/workflows/ci.yml
#182 had a copy/paste error from another project that uses "main" as the branch name which prevents the `checkout` action from running normally on the main project.
> Fixes cabal-install action

- .github/workflows/ci.yml
- cabal.haskell-ci
- stack-lts16.yaml
- stack-lts17.yaml
- stack.yaml
It looks like there were some issues with my last attempt at fixing the GitHub Actions-based CI (cf #183).
This PR should _hopefully_ address it by fixing the criteria under which the checkout action runs (I copy/pasted from another project without fully understanding what it was doing).
In addition to that, I've added a CI step to check against the latest Stackage LTS (17.5 at the time of writing), and I've bumped the LTS-16 and nightly resolvers to newer versions as well.
> Fixes GitHub Actions-based CI

- servant-auth-server/README.lhs
JS example in `XSRF and the frontend` missed a `}`
> Fix a JS example
